# Generated by Django 6.1.1 on 2026-09-19 11:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=512, upload_to=core.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.thumbnail_upload_path),
        ),
    ]
