# Generated by Django 6.1.1 on 2026-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_photo_image_alter_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration timestamp for customer gallery access.', null=True),
        ),
    ]
